"""Shared entity name normalization for NPCI statistics loaders."""

# Maps every known raw NPCI name variant to a single canonical form.
# All loaders import normalize_bank_name() from here.
BANK_NAME_MAP = {
    # ── ALL CAPS (NPCI occasionally returns uppercase names) ──────────────────
    "AIRTEL PAYMENTS BANK":                     "Airtel Payments Bank",
    "ANDHRA PRAGATHI GRAMEENA BANK":            "Andhra Pragathi Grameena Bank",
    "AU SMALL FINANCE BANK":                    "AU Small Finance Bank",
    "AXIS BANK":                                "Axis Bank",
    "AXIS BANK LTD":                            "Axis Bank",
    "AXIS BANK LTD.":                           "Axis Bank",
    "BANDHAN BANK LIMITED":                     "Bandhan Bank",
    "BANK OF BARODA":                           "Bank of Baroda",
    "BANK OF INDIA":                            "Bank of India",
    "BANK OF MAHARASHTRA":                      "Bank of Maharashtra",
    "BARODA UTTAR PRADESH GRAMIN BANK":         "Baroda UP Bank",
    "CANARA BANK":                              "Canara Bank",
    "CENTRAL BANK OF INDIA":                    "Central Bank of India",
    "CHAITANYA GODAVARI GRAMEENA BANK":         "Chaitanya Godavari Grameena Bank",
    "CITIBANK":                                 "Citibank",
    "CITY UNION BANK":                          "City Union Bank",
    "COSMOS BANK":                              "Cosmos Co-operative Bank",
    "DEUTSCHE BANK CORP":                       "Deutsche Bank",
    "DEVELOPMENT BANK OF SINGAPORE":            "Development Bank of Singapore",
    "EQUITAS SMALL FINANCE BANK":               "Equitas Small Finance Bank",
    "ESAF SMALL FINANCE BANK":                  "ESAF Small Finance Bank",
    "ESAF SMALL FINANCE BANK LTD":              "ESAF Small Finance Bank",
    "FEDERAL BANK":                             "Federal Bank",
    "FINCARE SMALL FINANCE BANK LTD":           "Fincare Small Finance Bank",
    "FINO PAYMENTS BANK":                       "Fino Payments Bank",
    "FINO PAYMENTS BANK LIMITED":               "Fino Payments Bank",
    "GARAGEPRENEURS INTERNET PRIVATE LIMITED":  "Garagepreneurs Internet Pvt Ltd",
    "HDFC BANK":                                "HDFC Bank",
    "HDFC BANK LTD":                            "HDFC Bank",
    "HDFC BANK LTD.":                           "HDFC Bank",
    "ICICI BANK":                               "ICICI Bank",
    "ICICI BANK LTD":                           "ICICI Bank",
    "IDBI BANK":                                "IDBI Bank",
    "IDBI BANK LIMITED":                        "IDBI Bank",
    "IDBI BANK LTD":                            "IDBI Bank",
    "IDFC BANK":                                "IDFC First Bank",
    "IDFC FIRST BANK":                          "IDFC First Bank",
    "INDIA POST PAYMENT BANK":                  "India Post Payments Bank",
    "INDIA POST PAYMENTS BANK LIMITED":         "India Post Payments Bank",
    "INDIAN BANK":                              "Indian Bank",
    "INDIAN OVERSEAS BANK":                     "Indian Overseas Bank",
    "INDUSIND BANK":                            "IndusInd Bank",
    "JAMMU AND KASHMIR BANK":                   "Jammu & Kashmir Bank",
    "JIO PAYMENTS BANK LTD":                    "Jio Payments Bank",
    "KARNATAKA BANK":                           "Karnataka Bank",
    "KARUR VYSYA BANK":                         "Karur Vysya Bank",
    "KERALA GRAMIN BANK":                       "Kerala Gramin Bank",
    "KERALA GRAMIN BANK -IMPS":                 "Kerala Gramin Bank",
    "KOTAK MAHINDRA BANK":                      "Kotak Mahindra Bank",
    "MADHYA BIHAR GRAMIN BANK":                 "Madhya Bihar Gramin Bank",
    "MAHARASHTRA GRAMIN BANK":                  "Maharashtra Gramin Bank",
    "NSDL PAYMENTS BANK LIMITED":               "NSDL Payments Bank",
    "ONE MOBIKWIK SYSTEMS LIMITED":             "One Mobikwik Systems",
    "PAYTM PAYMENTS BANK":                      "Paytm Payments Bank",
    "PRAGATHI KRISHNA GRAMIN BANK-IMPS":        "Pragathi Krishna Gramin Bank",
    "PUNJAB AND SIND BANK":                     "Punjab & Sind Bank",
    "PUNJAB NATIONAL BANK":                     "Punjab National Bank",
    "RAJASTHAN MARUDHARA GRAMIN BANK":          "Rajasthan Marudhara Gramin Bank",
    "RBL BANK":                                 "RBL Bank",
    "RBL BANK LIMITED":                         "RBL Bank",
    "SARASWAT CO-OPERATIVE BANK":               "Saraswat Co-operative Bank",
    "SARVA HARYANA GRAMIN BANK":                "Sarva Haryana Gramin Bank",
    "SARVA U.P. GRAMIN BANK":                   "Sarva U.P. Gramin Bank",
    "SOUTH INDIAN BANK":                        "South Indian Bank",
    "STANDARD CHARTERED":                       "Standard Chartered Bank",
    "STANDARD CHARTERED BANK":                  "Standard Chartered Bank",
    "STATE BANK OF INDIA":                      "State Bank of India",
    "SURYODAY SMALL FINANCE BANK LIMITED":      "Suryoday Small Finance Bank",
    "TAMILNAAD MERCANTILE BANK":                "Tamilnad Mercantile Bank",
    "TELANGANA GRAMEENA BANK":                  "Telangana Grameena Bank",
    "THE COSMOS CO-OPERATIVE BANK LTD":         "Cosmos Co-operative Bank",
    "THE SOUTH INDIAN BANK":                    "South Indian Bank",
    "TJSB SAHAKARI BANK LIMITED":               "TJSB Sahakari Bank",
    "TRI O TECH SOLUTIONS PRIVATE LIMITED":     "Tri O Tech Solutions",
    "UCO BANK":                                 "UCO Bank",
    "UJJIVAN SMALL FINANCE BANK LIMITED":       "Ujjivan Small Finance Bank",
    "UNION BANK OF INDIA":                      "Union Bank of India",
    "UTTAR BIHAR GRAMIN BANK":                  "Uttar Bihar Gramin Bank",
    "YES BANK LTD":                             "Yes Bank",
    # ── Mixed / sentence-case inconsistencies ─────────────────────────────────
    "AU small Finance Bank":                    "AU Small Finance Bank",
    "AU Small Finance Bank (Erstwhile Fincare)":"AU Small Finance Bank",
    "Au Small Finance Bank":                    "AU Small Finance Bank",
    "AXIS Bank Ltd.":                           "Axis Bank",
    "Airtel Payments Bank Limited":             "Airtel Payments Bank",
    "Airtel Payments Bank Ltd":                 "Airtel Payments Bank",
    "Airtel Payments Bank Ltd.":                "Airtel Payments Bank",
    "Andhra bank":                              "Andhra Bank",
    "Andhra Pradesh Grameena Vikas Bank - IMPS":"Andhra Pradesh Grameena Vikas Bank",
    "Andhra Pradesh Grameena Vikas Bank - Imps":"Andhra Pradesh Grameena Vikas Bank",
    "Assam Gramin Vikash Bank-IMPS.":           "Assam Gramin Vikash Bank",
    "Axis Bank Ltd":                            "Axis Bank",
    "Axis Bank Ltd.":                           "Axis Bank",
    "Axis bank Ltd.":                           "Axis Bank",
    "BANDHAN BANK":                             "Bandhan Bank",
    "Bandhan Bank Limited":                     "Bandhan Bank",
    "Bandhan Bank Ltd.":                        "Bandhan Bank",
    "Bandhan Bank limited":                     "Bandhan Bank",
    "Bank Of Baroda":                           "Bank of Baroda",
    "Bank Of India":                            "Bank of India",
    "Bank Of Maharashtra":                      "Bank of Maharashtra",
    "Baroda U.P. Bank":                         "Baroda UP Bank",
    "Baroda U.P. Bank (Erstwhile Baroda Uttar Pradesh Gramin Bank)": "Baroda UP Bank",
    "Baroda UP Gramin Bank":                    "Baroda UP Bank",
    "Baroda Uttar Pradesh Gramin Bank":         "Baroda UP Bank",
    "CITI":                                     "Citibank",
    "CITI Bank":                                "Citibank",
    "CITI bank":                                "Citibank",
    "CITIBANK CORPORATE":                       "Citibank Corporate",
    "CITIBank":                                 "Citibank",
    "Citi Bank":                                "Citibank",
    "Central Bank Of India":                    "Central Bank of India",
    "Cosmos Bank":                              "Cosmos Co-operative Bank",
    "DBS Bank India Limited":                   "DBS Bank India",
    "DBS Bank India Ltd.":                      "DBS Bank India",
    "DBS Bank Ltd":                             "DBS Bank India",
    "Dbs Bank India Limited":                   "DBS Bank India",
    "Equitas Bank":                             "Equitas Small Finance Bank",
    "Equitas Small Finance Bank Ltd":           "Equitas Small Finance Bank",
    "ESAF Small Finance Bank Ltd":              "ESAF Small Finance Bank",
    "ESAF Small Finance Bank Ltd.":             "ESAF Small Finance Bank",
    "Esaf Small Finance Bank Ltd":              "ESAF Small Finance Bank",
    "Fampay (PPI)":                             "FamPay PPI",
    "Federal Bank Ltd.":                        "Federal Bank",
    "Federal bank Ltd.":                        "Federal Bank",
    "Fincare Small Finance Bank Limited":       "Fincare Small Finance Bank",
    "Fincare Small Finance Bank Ltd":           "Fincare Small Finance Bank",
    "Fino Payments Bank Limited":               "Fino Payments Bank",
    "Fino Payments Bank Limited FIP":           "Fino Payments Bank",
    "Fino Payments Bank Ltd.":                  "Fino Payments Bank",
    "Garagepreneurs Internet Private Limited":  "Garagepreneurs Internet Pvt Ltd",
    "HDFC Bank Ltd":                            "HDFC Bank",
    "HDFC Bank Ltd.":                           "HDFC Bank",
    "Hdfc Bank Ltd.":                           "HDFC Bank",
    "ICICI Bank Ltd":                           "ICICI Bank",
    "ICICI Bank Ltd.":                          "ICICI Bank",
    "Icici Bank Credit Card":                   "ICICI Bank Credit Card",
    "Icici Bank Ltd.":                          "ICICI Bank",
    "IDBI Bank Limited":                        "IDBI Bank",
    "IDBI Bank Ltd.":                           "IDBI Bank",
    "Idbi Bank Ltd.":                           "IDBI Bank",
    "IDFC Bank Ltd.":                           "IDFC First Bank",
    "IDFC FIRST Bank":                          "IDFC First Bank",
    "IDFC First Bank Ltd":                      "IDFC First Bank",
    "Idfc Bank Ltd.":                           "IDFC First Bank",
    "India Post Payment Bank":                  "India Post Payments Bank",
    "India Post Payments Bank Limited":         "India Post Payments Bank",
    "India Post Payments Bank Ltd":             "India Post Payments Bank",
    "India Post Payments Bank Ltd.":            "India Post Payments Bank",
    "IndusInd Bank Ltd.":                       "IndusInd Bank",
    "Indusind Bank":                            "IndusInd Bank",
    "Indusind Bank Ltd.":                       "IndusInd Bank",
    "JIO Payments Bank Ltd":                    "Jio Payments Bank",
    "Jammu And Kashmir Bank":                   "Jammu & Kashmir Bank",
    "Jammu and Kashmir Bank":                   "Jammu & Kashmir Bank",
    "Jio Payments Bank Ltd":                    "Jio Payments Bank",
    "Jio Payments Bank Ltd - IMPS":             "Jio Payments Bank",
    "Jio Payments Bank Limited":                "Jio Payments Bank",
    "Jio Payments Bank limited":                "Jio Payments Bank",
    "Karnataka Bank Ltd":                       "Karnataka Bank",
    "Karnataka Grameena Bank":                  "Karnataka Gramin Bank",
    "Karnataka Gramin Bank (Erstwhile Pragathi Krishna Gramin Bank)": "Karnataka Gramin Bank",
    "Karnatak vikas Gramin Bank":               "Karnataka Vikas Grameena Bank",
    "NSDL Payments Bank Limited":               "NSDL Payments Bank",
    "Nsdl Payments Bank Limited":               "NSDL Payments Bank",
    "North East Small Finance Bank Acquirer":   "Slice Small Finance Bank",
    "North East Small Finance Bank Limited - IMPS": "Slice Small Finance Bank",
    "North East Small Finance Bank Ltd":        "Slice Small Finance Bank",
    "One Mobikwik Systems Limited":             "One Mobikwik Systems",
    "One Mobikwik Systems Pvt - Ltd":           "One Mobikwik Systems",
    "PayTM Payments Bank Ltd":                  "Paytm Payments Bank",
    "Pragathi Krishna Gramin Bank-IMPS":        "Pragathi Krishna Gramin Bank",
    "Prathama UP Gramin Bank(Erstwhile Sarva UP Gramin Bank)": "Sarva U.P. Gramin Bank",
    "Punjab And Sind Bank":                     "Punjab & Sind Bank",
    "Punjab and Sind Bank":                     "Punjab & Sind Bank",
    "Punjab national Bank":                     "Punjab National Bank",
    "RBL":                                      "RBL Bank",
    "RBL Bank LTD":                             "RBL Bank",
    "RBL Bank Limited":                         "RBL Bank",
    "RBL Bank Ltd":                             "RBL Bank",
    "RBL Bank Ltd.":                            "RBL Bank",
    "RBL bank":                                 "RBL Bank",
    "Rbl Bank Ltd.":                            "RBL Bank",
    "Saraswat Bank":                            "Saraswat Co-operative Bank",
    "Saraswat Co-Operative Bank":               "Saraswat Co-operative Bank",
    "Saraswat Co-operative Bank Ltd.":          "Saraswat Co-operative Bank",
    "Slice Bank":                               "Slice Small Finance Bank",
    "Slice Small Finance Bank Acquirer":        "Slice Small Finance Bank",
    "Slice Small Finance Bank Ltd":             "Slice Small Finance Bank",
    "Standard Chartered":                       "Standard Chartered Bank",
    "State Bank Of India":                      "State Bank of India",
    "State bank Of India":                      "State Bank of India",
    "Suryoday Small Finance Bank Limited":      "Suryoday Small Finance Bank",
    "Suryodaya Small Finance Bank Limited":     "Suryoday Small Finance Bank",
    "Tamilnad Mercantile Bank Limited":         "Tamilnad Mercantile Bank",
    "Tamilnad Mercantile Bank Ltd.":            "Tamilnad Mercantile Bank",
    "Telangana Grameena bank":                  "Telangana Grameena Bank",
    "The Akola District Central Co-Op. Bank Ltd. Akola": "The Akola District Central Co-operative Bank",
    "The Akola District Central Co-op. Bank Ltd. Akola": "The Akola District Central Co-operative Bank",
    "The Cosmos Co-Operative Bank Ltd":         "Cosmos Co-operative Bank",
    "The Jammu & Kashmir Bank Limited":         "Jammu & Kashmir Bank",
    "The Jammu And Kashmir Bank Ltd":           "Jammu & Kashmir Bank",
    "The South Indian Bank":                    "South Indian Bank",
    "The South Indian Bank Limited":            "South Indian Bank",
    "Tri O Tech Solutions Private Limited":     "Tri O Tech Solutions",
    "Tri O Tech Solutions Private Limited (PPI)": "Tri O Tech Solutions",
    "Tri O Tech Solutions Private Limited PPI": "Tri O Tech Solutions",
    "Tri O Tech Solutions Private Ltd.":        "Tri O Tech Solutions",
    "Uco Bank":                                 "UCO Bank",
    "Ujjivan Small Finance Bank Limited":       "Ujjivan Small Finance Bank",
    "Union Bank Of India":                      "Union Bank of India",
    "Unity Small Finance Bank Limited":         "Unity Small Finance Bank",
    "YES Bank - Amazon pay":                    "Yes Bank",
    "YES Bank Ltd.":                            "Yes Bank",
    "Yes Bank Ltd":                             "Yes Bank",
    "Yes Bank Ltd.":                            "Yes Bank",
    "Yes Bank Limited":                         "Yes Bank",
    "Yes Bank Limited YBP":                     "Yes Bank",
    "Yes bank Ltd.":                            "Yes Bank",
    # ── Bank renames: old name → canonical successor ──────────────────────────
    "Jharkhand Rajya Gramin Bank(Erstwhile Vanachal Gramin Bank)": "Vananchal Gramin Bank",
    # Slice merged into North East SFB (2023) and the combined bank renamed to
    # Slice SFB (2025). NPCI has used five labels for this one entity across
    # months/tabs; everything folds to the current name, one continuous series.
    "North East Small Finance Bank":            "Slice Small Finance Bank",
    "North East Small Finance Bank Limited":    "Slice Small Finance Bank",
    "Slice Small Finance Bank Limited":         "Slice Small Finance Bank",
    "Slice Small Finance Bank Limited(North East Small Finance Bank Limited)": "Slice Small Finance Bank",
}


# Case-insensitive fallback index, built from both the map's keys and its
# canonical values. NPCI re-cases existing labels between months ("Indian Bank"
# → "INDIAN Bank", "IDFC First Bank" → "IDFC First BANK"), which silently splits
# a bank into two series and halves its totals. Indexing the values too means a
# pure re-casing of a name we already know resolves without a new map entry.
# Verified unambiguous: no two entries here disagree on the canonical form.
_CASEFOLD_MAP = {}
for _raw, _canonical in BANK_NAME_MAP.items():
    _CASEFOLD_MAP.setdefault(_raw.casefold(), _canonical)
for _canonical in BANK_NAME_MAP.values():
    _CASEFOLD_MAP.setdefault(_canonical.casefold(), _canonical)


def normalize_bank_name(name: str) -> str:
    """Return the canonical bank/entity name, or the original if not in the map.

    Input is stripped first: NPCI has published labels with trailing spaces,
    which would otherwise bypass the map entirely. Exact matches win; a
    case-only variant of a known name falls back to _CASEFOLD_MAP."""
    name = (name or "").strip()
    if name in BANK_NAME_MAP:
        return BANK_NAME_MAP[name]
    return _CASEFOLD_MAP.get(name.casefold(), name)
